In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
car= pd.read_csv(r'D:\JUPYTER NOTEBOOK--1\DSMP-2\FEATURE_ENGINEERING\datasets\cars.csv')
car.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [71]:
car=car.drop(columns=['km_driven','owner'])

In [72]:
car.head()

     brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [73]:
X=car.iloc[:,:2]
y=car.iloc[:,-1]

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [75]:
from sklearn.preprocessing import OneHotEncoder

In [76]:
ohe=OneHotEncoder()

In [77]:
# ohe.fit_transform(X_train)

In [78]:
X_train_ohe=ohe.fit_transform(X_train).toarray()
X_train

         brand    fuel
6518      Tata  Petrol
6144     Honda  Petrol
6381   Hyundai  Diesel
438     Maruti  Diesel
5939    Maruti  Petrol
...        ...     ...
5226  Mahindra  Diesel
5390    Maruti  Diesel
860    Hyundai  Petrol
7603    Maruti  Diesel
7270    Maruti  Petrol

[6502 rows x 2 columns]

In [79]:
X_train_ohe.shape

(6502, 36)

In [80]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [81]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [82]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [87]:
X_train_df = pd.DataFrame(
    X_train_ohe,
    columns=ohe.get_feature_names_out()
)

In [93]:
X_train_df.columns

Index(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia', 'brand_Land',
       'brand_Lexus', 'brand_MG', 'brand_Mahindra', 'brand_Maruti',
       'brand_Mercedes-Benz', 'brand_Mitsubishi', 'brand_Nissan', 'brand_Opel',
       'brand_Peugeot', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo', 'fuel_CNG',
       'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'],
      dtype='object')

In [96]:
X_train_df.sample(5)

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
5846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
222,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5178,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## FULL CODE AS HERE WE CAN CHNAGE AT ANY LINE

In [101]:
# -------------------------------------------------------------
# 1) Import Libraries
# -------------------------------------------------------------
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# -------------------------------------------------------------
# 2) Load Dataset
# -------------------------------------------------------------
car = pd.read_csv(r'D:\JUPYTER NOTEBOOK--1\DSMP-2\FEATURE_ENGINEERING\datasets\cars.csv')

# Display first 5 rows
print("Dataset Preview:")
display(car.head())

# -------------------------------------------------------------
# 3) Drop Unwanted Columns
# -------------------------------------------------------------
car = car.drop(columns=['km_driven', 'owner'])

# -------------------------------------------------------------
# 4) Split Features & Target
# -------------------------------------------------------------
X = car.drop('selling_price', axis=1)
y = car['selling_price']

# -------------------------------------------------------------
# 5) Identify Categorical Columns
# -------------------------------------------------------------
categorical_cols = X.select_dtypes(include='object').columns.tolist()

print("\nCategorical Columns:", categorical_cols)

# -------------------------------------------------------------
# 6) Create OneHotEncoder with drop='first'
#    - drop='first' removes the first category of each feature 
#      to avoid dummy-variable multicollinearity
# -------------------------------------------------------------
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')

# -------------------------------------------------------------
# 7) Use ColumnTransformer (Best practice)
# -------------------------------------------------------------
ct = ColumnTransformer(
    transformers=[
        ("ohe_encoder", ohe, categorical_cols)
    ],
    remainder='passthrough'   # keep numerical columns as they are
)

# -------------------------------------------------------------
# 8) Train-Test Split
# -------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------------------------------------
# 9) Fit on Train, Transform Train
# -------------------------------------------------------------
X_train_ohe = ct.fit_transform(X_train)

print("\nShape of Transformed Training Data:", X_train_ohe.shape)

# -------------------------------------------------------------
# 10) Build DataFrame of Encoded Columns
# -------------------------------------------------------------
# Get names of OHE-generated columns
ohe_feature_names = ct.named_transformers_['ohe_encoder'].get_feature_names_out(categorical_cols)

# Get names of numerical columns (passed through unchanged)
num_cols = [col for col in X_train.columns if col not in categorical_cols]

# Combine feature names
final_feature_names = list(ohe_feature_names) + num_cols

# Create final encoded DataFrame
X_train_df = pd.DataFrame(X_train_ohe, columns=final_feature_names)

Dataset Preview:

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

Categorical Columns: ['brand', 'fuel']

Shape of Transformed Training Data: (6502, 34)

In [102]:
print("\nEncoded Training DataFrame (Sample):")
X_train_df.sample(5)

Encoded Training DataFrame (Sample):

,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,brand_Honda,...,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_Diesel,fuel_LPG,fuel_Petrol
5493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3715,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2696,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0