In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [2]:
car= pd.read_csv(r'D:\JUPYTER NOTEBOOK--1\DSMP-2\FEATURE_ENGINEERING\datasets\cars.csv')
car.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

### transforming the columns without transformer or pipeline

In [3]:
df=car.copy()
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['brand'].value_counts()
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [5]:
X_train,X_test,y_train,y_test=train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
    )

In [6]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [7]:
# APPLYING THE ORDINAL ENCODER
oe=OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner=oe.fit_transform(X_train.loc[:,['owner']])
X_test_owner=oe.fit_transform(X_test.loc[:,['owner']])

In [8]:
# CONVERT TO  THE DF
X_train_owner_df=pd.DataFrame(X_train_owner,columns=oe.get_feature_names_out())
X_test_owner_df=pd.DataFrame(X_test_owner,columns=oe.get_feature_names_out())

In [9]:
X_train_owner_df.head()

   owner
0    4.0
1    3.0
2    1.0
3    3.0
4    4.0

In [10]:
# APPLYING THE OHE TO BRAND AND FUEL
ohe=OneHotEncoder(sparse_output=False)

X_train_brand_fuel=ohe.fit_transform(X_train[['brand','fuel']])
X_test_brand_fuel=ohe.transform(X_test[['brand','fuel']])

In [11]:
# converting to dataframe
X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel, columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel, columns=ohe.get_feature_names_out())

In [12]:
X_train_brand_fuel_df.head()

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [13]:
X_train_rem = X_train.drop(columns=['brand', 'fuel', 'owner'],inplace=True)
X_test_rem = X_test.drop(columns=['brand', 'fuel', 'owner'],inplace=True)

In [14]:
X_train = pd.concat([X_train_rem, X_train_owner_df, X_train_brand_fuel_df],axis=1)
X_test = pd.concat([X_test_rem, X_test_owner_df, X_test_brand_fuel_df],axis=1)

In [15]:
X_train.head()

,owner,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
X_train_rem

### APPLYING THE COLUMN TANSFORMER THROUGH PIPELINE

In [17]:
from sklearn.compose import ColumnTransformer

In [18]:
df1=car.copy()

In [19]:
df1.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
)

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ("ordinal",
         OrdinalEncoder(categories=[[
             'Test Drive Car',
             'Fourth & Above Owner',
             'Third Owner',
             'Second Owner',
             'First Owner'
         ]]),
         ['owner']
        ),

        ("onehot",
         OneHotEncoder(sparse_output=False),
         ['brand', 'fuel']
        )
    ],
    remainder="passthrough"
)
# setting to get a pandas df
transformer.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal',
                                 OrdinalEncoder(categories=[['Test Drive Car',
                                                             'Fourth & Above '
                                                             'Owner',
                                                             'Third Owner',
                                                             'Second Owner',
                                                             'First Owner']]),
                                 ['owner']),
                                ('onehot', OneHotEncoder(sparse_output=False),
                                 ['brand', 'fuel'])])

In [32]:
X_train_transformed=transformer.fit_transform(X_train)
X_test_transformed=transformer.transform(X_test)

In [33]:
pd.DataFrame(X_train_transformed,columns=transformer.get_feature_names_out())

,ordinal__owner,onehot__brand_Ambassador,onehot__brand_Ashok,onehot__brand_Audi,onehot__brand_BMW,onehot__brand_Chevrolet,onehot__brand_Daewoo,onehot__brand_Datsun,onehot__brand_Fiat,onehot__brand_Force,...,onehot__brand_Skoda,onehot__brand_Tata,onehot__brand_Toyota,onehot__brand_Volkswagen,onehot__brand_Volvo,onehot__fuel_CNG,onehot__fuel_Diesel,onehot__fuel_LPG,onehot__fuel_Petrol,remainder__km_driven
6518,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2560
6144,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,80000
6381,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,150000
438,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000
5939,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000
5390,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,80000
860,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,35000
7603,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27000
7270,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,70000

In [34]:
transformer.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal',
                                 OrdinalEncoder(categories=[['Test Drive Car',
                                                             'Fourth & Above '
                                                             'Owner',
                                                             'Third Owner',
                                                             'Second Owner',
                                                             'First Owner']]),
                                 ['owner']),
                                ('onehot', OneHotEncoder(sparse_output=False),
                                 ['brand', 'fuel'])])

In [35]:
transformer.fit_transform(X_train).head()

,ordinal__owner,onehot__brand_Ambassador,onehot__brand_Ashok,onehot__brand_Audi,onehot__brand_BMW,onehot__brand_Chevrolet,onehot__brand_Daewoo,onehot__brand_Datsun,onehot__brand_Fiat,onehot__brand_Force,...,onehot__brand_Skoda,onehot__brand_Tata,onehot__brand_Toyota,onehot__brand_Volkswagen,onehot__brand_Volvo,onehot__fuel_CNG,onehot__fuel_Diesel,onehot__fuel_LPG,onehot__fuel_Petrol,remainder__km_driven
6518,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2560
6144,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,80000
6381,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,150000
438,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000
5939,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25000

In [26]:
# X_train_transformed

In [27]:
# transformer.get_feature_names_out()

In [28]:
transformer.named_transformers_

{'ordinal': OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                             'Third Owner', 'Second Owner', 'First Owner']]),
 'onehot': OneHotEncoder(sparse_output=False),
 'remainder': FunctionTransformer(accept_sparse=True, check_inverse=False,
                     feature_names_out='one-to-one')}

In [29]:
transformer.transformers_

[('ordinal',
  OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                              'Third Owner', 'Second Owner', 'First Owner']]),
  ['owner']),
 ('onehot', OneHotEncoder(sparse_output=False), ['brand', 'fuel']),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  ['km_driven'])]

In [36]:
transformer.named_transformers_["ordinal"]

OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                            'Third Owner', 'Second Owner', 'First Owner']])

In [38]:
transformer.named_transformers_["onehot"]

OneHotEncoder(sparse_output=False)

## Sklearn - PIPELINE

In [84]:
df=car.copy()

In [85]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [86]:
df.shape

(8128, 5)

# Introducing Missing Values for Data Preprocessing (Line-by-Line Explanation)

This code is commonly used in **data preprocessing and machine learning** to **simulate real-world data issues**, especially **missing values**.

---

## 🔹 Dataset Columns

The DataFrame `df` contains the following columns:

```
brand | km_driven | fuel | owner | selling_price
```

---

## 🔹 1. Fixing Randomness (Reproducibility)

```python
np.random.seed(42)
```

### What this does

* Sets a **fixed random seed**.
* Ensures the **same random rows are selected every time** the code is run.

### Why it’s important

* Guarantees **reproducibility**.
* Essential for **ML experiments and debugging**.

---

## 🔹 2. Creating Missing Values in `km_driven` (5%)

```python
missing_km_indices = np.random.choice(
    df.index,
    size=int(0.05 * len(df)),
    replace=False
)
```

### Step-by-step explanation

1. `df.index`

   * Provides all row indices of the DataFrame
   * Example: `[0, 1, 2, 3, ...]`

2. `0.05 * len(df)`

   * Calculates **5% of total rows**
   * Example: 1000 rows → 50 rows

3. `np.random.choice(...)`

   * Randomly selects **5% of row indices**
   * `replace=False` ensures **no duplicate rows**

### Result

* `missing_km_indices` stores **random row positions**.

---

### 🔹 Assigning NaN to `km_driven`

```python
df.loc[missing_km_indices, 'km_driven'] = np.nan
```

### What happens

* At the selected rows, `km_driven` values are replaced with `NaN`.

### Outcome

* **5% of `km_driven` becomes missing**
* Simulates **real-world incomplete numerical data**

---

## 🔹 3. Creating Missing Values in `owner` (1%)

```python
missing_owner_indices = np.random.choice(
    df.index,
    size=int(0.01 * len(df)),
    replace=False
)
```

### Explanation

* Same logic as before
* Selects **1% of total rows**

---

### 🔹 Assigning NaN to `owner`

```python
df.loc[missing_owner_indices, 'owner'] = np.nan
```

### Result

* **1% of `owner` values become NaN**
* Simulates **missing categorical data**

---

## 🔹 Why This Is Done in Machine Learning

This approach is used to:

✔️ Simulate **real-world dirty datasets**
✔️ Practice **missing value handling**
✔️ Test **imputation strategies**
✔️ Build **robust ML pipelines**

---

## 🔹 Example After Execution

| brand  | km_driven | fuel   | owner       | selling_price |
| ------ | --------- | ------ | ----------- | ------------- |
| Maruti | NaN       | Diesel | First Owner | 450000        |
| Skoda  | 120000    | Diesel | NaN         | 370000        |
| Honda  | 140000    | Petrol | Third Owner | 158000        |

---

## 🔹 Typical Next Steps

After introducing missing values, you usually:

* Impute `km_driven` using **mean / median**
* Impute `owner` using **most frequent value**
* Use `sklearn.impute.SimpleImputer`
* Add preprocessing to a **pipeline**


**This code intentionally introduces missing values into numerical and categorical columns to practice real-world data preprocessing and model robustness.**

In [87]:
np.random.seed(42)
missing_km_indices=np.random.choice(df.index,size=int(0.05* len(df)),replace=False)
df.loc[missing_km_indices,'km_driven']=np.nan

# INtroduce missing values in "owner" column (1% missing values)

missing_owner_indices=np.random.choice(df.index,size=int(0.01*len(df)),replace=False)
df.loc[missing_owner_indices,'owner']=np.nan

In [88]:
df.isnull().sum()

brand              0
km_driven        406
fuel               0
owner             81
selling_price      0
dtype: int64

In [89]:
X_train,X_test,y_train,y_test=train_test_split(
        df.drop(columns=['selling_price']),
        df['selling_price'],
        test_size=0.2,
        random_state=42
)

In [90]:
X_test.isnull().sum()

brand          0
km_driven    406
fuel           0
owner         21
dtype: int64

In [91]:
X_train.isnull().sum()

brand         0
km_driven     0
fuel          0
owner        60
dtype: int64

#### NOW WE WILL MAKE A PIPELINE THAT WILL PERFORM THESE OPERATIONS.

1.Missing value imputation

2.encoding categorical variables

3.scaling

4.feature selection

5.model building

6.prediction

In [92]:
# 1. imputation transformer
trf1=ColumnTransformer([
    ('impute_km_driven',SimpleImputer(),[1]),
    ('impute_owner',SimpleImputer(strategy='most_frequent'),[3])],
                      remainder='passthrough'
)

In [93]:
#2. encoding categorical variables
trf2 = ColumnTransformer(
    [
        ("ordinal", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), [3]),
        ("onehot", OneHotEncoder(handle_unknown='ignore', sparse_output=False), [0,2])
    ],
    remainder='passthrough'
)

## 🔹 What Does This Transformation Do?

This transformation rescales the values of the **first 38 feature columns** so that each column’s values lie **between 0 and 1**.

- Each feature is scaled **independently**
- The **number of columns remains unchanged**
- Only the **scale of the values** is modified

Nothing more, nothing less.

---

## 🔹 What `MinMaxScaler` Actually Does (Mathematics)

For each feature column, `MinMaxScaler` applies the following formula:

\[
x_{\text{scaled}} = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
\]

### Where:
- \(x\) = original value  
- \(x_{\min}\) = minimum value of the feature  
- \(x_{\max}\) = maximum value of the feature  

This ensures:
- Minimum value → **0**
- Maximum value → **1**
- All other values are scaled proportionally

---

## 🔹 Effect of This Transformation

- Converts selected features into the range **[0, 1]**
- Preserves the **relative distribution and patterns** of each feature
- Prevents features with large magnitudes from dominating the model
- Improves learning stability for scale-sensitive algorithms

---

## 🔹 Why This Transformation Is Important

MinMax scaling ensures that **all features contribute equally** during model training, which is crucial for:

- Linear models  
- Distance-based algorithms (KNN, K-Means)  
- Gradient-descent-based models  
- Neural networks  
- Support Vector Machines (SVM)

---

## 🔹 Key Takeaway

This transformation applies **MinMax scaling** to the first 38 feature columns, converting their values into the range **[0, 1]**.  
It changes only **how large the numbers are**, not **the patterns they represent**.

---

### 🧠 One-Line Intuition

**MinMax scaling changes the scale of the data, not the meaning of the data.**

In [94]:
#3.scaling
trf3=ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,38))
])

In [95]:
# #4.feature selection
# trf4=SelectKBest(score_func=chi2,k=10)

In [96]:
# # Feature selectiona
# trf4 = SelectKBest(score_func=chi2,k=10)

In this pipeline, the scaling step applies MinMax scaling to the encoded feature set so that all selected features lie within the range [0,1]. This ensures that numerical features such as km_driven do not dominate the learning process due to their larger magnitude. Scaling preserves the relative distribution of each feature while improving model stability, convergence, and fair feature comparison. It modifies only the scale of the values, not their underlying relationships.

In [97]:
#5.train the model
trf5=RandomForestRegressor()

In [111]:
from sklearn.pipeline import Pipeline

pipe=Pipeline([
    ('imputer',trf1),
    ('encoder',trf2),
    ('scaler',trf3),
    # ('fselector',trf4),
    ('model',trf5)
    
])

In [112]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('imputer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_km_driven',
                                                  SimpleImputer(), [1]),
                                                 ('impute_owner',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [3])])),
                ('encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  [3]),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [0, 2])])),
                ('scaler',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 38, None))])),
                ('model', RandomForestRegressor())])

In [113]:
pipe.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [114]:
pipe.named_steps

{'imputer': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_km_driven', SimpleImputer(), [1]),
                                 ('impute_owner',
                                  SimpleImputer(strategy='most_frequent'),
                                  [3])]),
 'encoder': ColumnTransformer(remainder='passthrough',
                   transformers=[('ordinal',
                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                 unknown_value=-1),
                                  [3]),
                                 ('onehot',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [0, 2])]),
 'scaler': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 38, None))]),
 'model': RandomForestRegressor()}

In [115]:
y_pred=pipe.predict(X_test)
y_pred

array([443785.1863436, 779542.0442775, 779542.0442775, ...,
       443785.1863436, 443785.1863436, 443785.1863436])

In [117]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
r2*100

4.689886032055468